application: whiskeysphere
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /index.html
  static_files: static/index.html
  upload: static/index.html
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /404.html
  static_files: static/404.html
  upload: static/404.html
  
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
  
- url: /apple-touch-icon-114x114-precomposed.png
  static_files: static/apple-touch-icon-114x114-precomposed.png
  upload: static/apple-touch-icon-114x114-precomposed.png
  
- url: /apple-touch-icon-57x57-precomposed.png
  static_files: static/apple-touch-icon-57x57-precomposed.png
  upload: static/apple-touch-icon-57x57-precomposed.png
  
- url: /apple-touch-icon-72x72-precomposed.png
  static_files: static/apple-touch-icon-72x72-precomposed.png
  upload: static/apple-touch-icon-72x72-precomposed.png
  
- url: /apple-touch-icon-precomposed.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png
  
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /js
  static_dir: static/js
  
- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img
  
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: .*
  script: main.py